sudo: required
dist: trusty
services:
  - docker
before_install:
  # this checks if the current branch is present in the ALL_VERSIONS variable if exists early if not
  # means we can control which version branches are built without having to update each .travis.yml for new branches
  - if [ $(bash themes/pxdocs-tooling/deploy/scripts/should_build_branch.sh) == "no" ]; then exit 0; fi
  # update gcloud apt source
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  # install docker-ce and kubectl
  - sudo apt-get update -yq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -yq docker-ce kubectl
  # connect the GCLOUD_SERVICE_ACCOUNT_TOKEN, GCP_PROJECT_ID, GCP_ZONE and GCP_CLUSTER_ID vars -> gcloud and kubectl
  - bash themes/pxdocs-tooling/deploy/scripts/ci_connect.sh
script:
  # setup variables based on travis env
  - export BUILDER_IMAGE="pxdocs:$TRAVIS_COMMIT"
  - export SEARCH_INDEX_IMAGE="pxdocs-indexer:$TRAVIS_COMMIT"
  - export DEPLOYMENT_IMAGE="gcr.io/$GCP_PROJECT_ID/pxdocs-$TRAVIS_BRANCH:$TRAVIS_COMMIT"
  - export PARSED_BRANCH=$(echo -n "$TRAVIS_BRANCH" | sed 's/\./-/g')
  - export ALGOLIA_INDEX_NAME=$PARSED_BRANCH
  # publish site -> public & update the algolia index
  - make search-index
  # build the deployment image
  - cp -r themes/pxdocs-tooling/deploy/nginx nginx_build_folder
  - cp -r public nginx_build_folder/hugo_public
  - docker build -t $DEPLOYMENT_IMAGE nginx_build_folder
  - rm -rf nginx_build_folder
  # push the image to gcloud
  - gcloud docker -- push $DEPLOYMENT_IMAGE
notifications:
  email:
    recipients:
      - harsh@portworx.com
    on_success: change
    on_failure: always
