sudo: required
dist: trusty
services:
  - docker
before_install:
  # this checks if the current branch is present in the ALL_VERSIONS variable if exists early if not
  # means we can control which version branches are built without having to update each .travis.yml for new branches
  - if [ $(bash themes/pxdocs-tooling/deploy/scripts/should_build_branch.sh) == "no" ]; then exit 0; fi
  # update gcloud apt source
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  # install docker-ce and kubectl
  - sudo apt-get update -yq
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -yq docker-ce kubectl
  # connect the GCLOUD_SERVICE_ACCOUNT_TOKEN, GCP_PROJECT_ID, GCP_ZONE and GCP_CLUSTER_ID vars -> gcloud and kubectl
  - bash themes/pxdocs-tooling/deploy/scripts/ci_connect.sh
script:
  - export 
  - export IMAGE="gcr.io/$GCP_PROJECT_ID/pxdocs-$TRAVIS_BRANCH:$TRAVIS_COMMIT"
  - export SEARCH_INDEX_IMAGE="gcr.io/$GCP_PROJECT_ID/pxdocs-indexer:$TRAVIS_COMMIT"
  - export ALGOLIA_INDEX_NAME=$(echo -n "$TRAVIS_BRANCH" | sed 's/\./-/g')
  - make publish
  - make search-index
notifications:
  email:
    recipients:
      - harsh@portworx.com
    on_success: change
    on_failure: always
